### ISSUE TITLE
Boceto

### ISSUE THREAD

**Issue by walvarezc1981** [NicoleBahamonMartinez/Ciclo3DesarrolloSoftware#1]
- [ ] Hacer boceto individual para concertar  el frontend en HTML y CSS.

**Comment by OlgaLuciaDiaz** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario</title>
</head>
<body>
        <h1>Formulario Dueño</h1>
    <form action="">
        <label for="tipo de identificación">Tipo de Identificación</label> <br>
        <input type="text" id="tipo de identificación"><br>
        <label for="número de identificación">Número de Identificación</label><br>
        <input type="number" id="número de identificación"><br>
        <label for="nombres">Nombres</label><br>
        <input type="text" id="nombres"><br>
        <label for="apellidos">Apellidos</label><br>
        <input type="text" id="apellidos"><br>
        <label for="teléfono">Teléfono</label><br>
        <input type="number" id="teléfono"><br>
        <label for="correo electrónico">Correo Electrónico</label><br>
        <input type="text" id="correo electrónico"><br>
        <label for="dirección">Dirección</label><br>
        <input type="text" id="dirección"><br>
        <label for="ciudad">Ciudad</label><br>
        <input type="text" id="ciudad"><br>
        <label for="país">País</label><br>
        <input type="text" id="país"><br>  
        <input type="submit" value="Enviar Formulario"><br>
        <input type="reset" value="Resetear Formulario"><br>
    <h1>Mascota Felíz</h1>
    <img src="dueña.jpeg" alt="Imagen no encontrada">

    </form>
</body>
</htm
![dueña](https://user-images.githubusercontent.com/85802783/134802829-19ee39af-5671-41f5-8a18-30f086d10076.jpeg)
l>

**Comment by OlgaLuciaDiaz** [comment]
![dueña](https://user-images.githubusercontent.com/85802783/134802991-7251473b-be7c-4310-8d69-038fb1cdd1bf.jpeg)

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario</title>
</head>
<body>
        <h1>Formulario Dueño</h1>
    <form action="">
        <label for="tipo de identificación">Tipo de Identificación</label> <br>
        <input type="text" id="tipo de identificación"><br>
        <label for="número de identificación">Número de Identificación</label><br>
        <input type="number" id="número de identificación"><br>
        <label for="nombres">Nombres</label><br>
        <input type="text" id="nombres"><br>
        <label for="apellidos">Apellidos</label><br>
        <input type="text" id="apellidos"><br>
        <label for="teléfono">Teléfono</label><br>
        <input type="number" id="teléfono"><br>
        <label for="correo electrónico">Correo Electrónico</label><br>
        <input type="text" id="correo electrónico"><br>
        <label for="dirección">Dirección</label><br>
        <input type="text" id="dirección"><br>
        <label for="ciudad">Ciudad</label><br>
        <input type="text" id="ciudad"><br>
        <label for="país">País</label><br>
        <input type="text" id="país"><br>  
        <input type="submit" value="Enviar Formulario"><br>
        <input type="reset" value="Resetear Formulario"><br>
    <h1>Mascota Felíz</h1>
    <img src="dueña.jpeg" alt="Imagen no encontrada">

    </form>
</body>
</html>
